# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53677fcfd646a120a0b7cc9a5e8b99cbd3c0dee98c5f2ecc22f23b7e41b75051c334ffeced46d33f7214746c1f3c61592243375e3dc48319f55ee96e302489c3

test:
  secret_key_base: f8b810669f615dcb3bd01e3f176eb850323b7a0307887755f11ee4fa5341b2d4b7f8df677cfaa9823194028902b0d3e5f2b5a842308cb0c936daf470caee2e27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
